version: '3'

services:
  platform:
    build: ../agriworks_platform
    ports:
      - '4000:4000'
    volumes:
      - ../agriworks_platform:/platform
    networks:
      - agri
  portal:
    build: .
    environment:
      AGRIWORKS_API_HOST: "platform"
    ports:
      - '8080:8080'
    volumes:
      - .:/portal
    networks:
      - agri

networks:
  agri: {}
