version: '3'

services:
  platform:
    container_name: platform
    build: ../agriworks_platform
    ports:
      - '4000:4000'
    volumes:
      - ../agriworks_platform:/platform
    networks:
      - agri
  portal:
    container_name: portal
    build: .
    environment:
      AGRIWORKS_API_HOST: "platform"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '8080:8080'
    volumes:
      - .:/portal
      - /portal/node_modules
    networks:
      - agri

networks:
  agri: {}
