version: '3'

services:
  platform:
    build: ../agriworks_platform
    command: flask run
    environment:
      FLASK_ENV: development
      FLASK_APP: application.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 4000
    ports:
      - '4000:4000'
    volumes:
      - ../agriworks_platform:/platform
    networks:
      - agri
  portal:
    build: .
    command: yarn serve
    ports:
      - '8080:8080'
    volumes:
      - .:/portal
    networks:
      - agri

networks:
  agri: {}
