branch-defaults:
  master:
    environment: test
  PROD:
    environment: prod
environment-defaults:
  test:
    branch: null
    repository: null
  prod:
    branch: null
    repository: null
global:
  application_name: agriworks
  default_ec2_keyname: agriworks
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
